services:

  backend:
    build:
      context: ./upcycle_connect-api
      network: host
    container_name: upcycle-api
    env_file: ./upcycle_connect-api/.env
    volumes:
      - ${UPLOADS_HOST_PATH}:/app/uploads
      - ${INVOICES_HOST_PATH}:/app/invoices
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      network: host
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_STRIPE_PUBLISHABLE_KEY: ${VITE_STRIPE_PUBLISHABLE_KEY}
        VITE_ONESIGNAL_APP_ID: ${VITE_ONESIGNAL_APP_ID}
    container_name: upcycle-nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
