services:

  backend:
    build: ./upcycle_connect-api
    container_name: upcycle-api
    env_file: ./upcycle_connect-api/.env
    ports:
      - "8084:8084"
    volumes:
      - ${UPLOADS_HOST_PATH}:/app/uploads
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-}
    container_name: upcycle-nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
