DELETE FROM REPORT            WHERE id_announcement IN (SELECT id_announcement FROM ANNOUNCEMENT WHERE id_category IS NULL);
DELETE FROM USER_ANNOUNCEMENT WHERE id_announcement IN (SELECT id_announcement FROM ANNOUNCEMENT WHERE id_category IS NULL);
DELETE FROM ANNOUNCEMENT_LOCKER WHERE id_announcement IN (SELECT id_announcement FROM ANNOUNCEMENT WHERE id_category IS NULL);
DELETE FROM DOCUMENT          WHERE category          IN (SELECT id_announcement FROM ANNOUNCEMENT WHERE id_category IS NULL);
DELETE FROM ANNOUNCEMENT WHERE id_category IS NULL;
ALTER TABLE ANNOUNCEMENT MODIFY COLUMN id_category CHAR(36) NOT NULL;
