SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS SUB_SUB_PLAN;
DROP TABLE IF EXISTS USER_SUBSCRIPTION;

DROP TABLE IF EXISTS PAYEMENT_PROJECT;
DROP TABLE IF EXISTS PAYEMENT_EVENT;
DROP TABLE IF EXISTS PAYEMENT_FORMATION;
DROP TABLE IF EXISTS USER_PAYEMENT;

DROP TABLE IF EXISTS USER_NOTIFICATION;
DROP TABLE IF EXISTS USER_TICKET;

DROP TABLE IF EXISTS USER_EVENT_INSCRIPTION;
DROP TABLE IF EXISTS USER_EVENT;

DROP TABLE IF EXISTS USER_FORMATION_INSCRIPTION_PAYEMENT;
DROP TABLE IF EXISTS USER_FORMATION_INSCRIPTION;
DROP TABLE IF EXISTS USER_FORMATION_CREATE;
DROP TABLE IF EXISTS USER_FORMATION_FORMATER;

DROP TABLE IF EXISTS USER_PROJECT_UPDOWN;
DROP TABLE IF EXISTS USER_PROJECT_INSCRIPTION;
DROP TABLE IF EXISTS USER_PROJECT_CREATE;

DROP TABLE IF EXISTS TOPIC_POST;
DROP TABLE IF EXISTS USER_TOPIC;

DROP TABLE IF EXISTS USER_ADVICE;

DROP TABLE IF EXISTS ANNOUNCEMENT_LOCKER;
DROP TABLE IF EXISTS USER_ANNOUNCEMENT;

DROP TABLE IF EXISTS USER_ROLE;

DROP TABLE IF EXISTS REPORT_POST;
DROP TABLE IF EXISTS REPORT_TOPIC;
DROP TABLE IF EXISTS REPORT_ANNOUCEMENT;

DROP TABLE IF EXISTS NOTIFICATION;
DROP TABLE IF EXISTS TICKET;
DROP TABLE IF EXISTS EVENT;
DROP TABLE IF EXISTS FORMATION;
DROP TABLE IF EXISTS PROJECT;
DROP TABLE IF EXISTS POST;
DROP TABLE IF EXISTS TOPIC;
DROP TABLE IF EXISTS ADVICE;

DROP TABLE IF EXISTS SUBSCRIPTION;
DROP TABLE IF EXISTS SUBSCRIPTION_PLANS;

DROP TABLE IF EXISTS PAYEMENT;
DROP TABLE IF EXISTS LOCKER;
DROP TABLE IF EXISTS ANNOUNCEMENT;
DROP TABLE IF EXISTS DOCUMENT;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS USER;

SET FOREIGN_KEY_CHECKS = 1;