upstream backend_api {
    server backend:8084;
}

server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 60s;

    client_max_body_size 20m;

    location /api/ {
        proxy_pass http://backend_api/;
    }

    location /uploads/ {
        proxy_pass http://backend_api/uploads/;
    }

    location /webhooks/ {
        proxy_pass http://backend_api/webhooks/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
