SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS user_sanctions;
DROP TABLE IF EXISTS user_subscription;
DROP TABLE IF EXISTS user_role;
DROP TABLE IF EXISTS user_project_updown;
DROP TABLE IF EXISTS user_project_inscription;
DROP TABLE IF EXISTS user_payement;
DROP TABLE IF EXISTS user_notification;
DROP TABLE IF EXISTS user_formation_inscription_payement;
DROP TABLE IF EXISTS user_formation_inscription;
DROP TABLE IF EXISTS user_event_inscription;
DROP TABLE IF EXISTS user_announcement;
DROP TABLE IF EXISTS user_advice;
DROP TABLE IF EXISTS topic_post;
DROP TABLE IF EXISTS sub_sub_plan;
DROP TABLE IF EXISTS role_permission;
DROP TABLE IF EXISTS report;
DROP TABLE IF EXISTS payement_project;
DROP TABLE IF EXISTS payement_formation;
DROP TABLE IF EXISTS payement_event;
DROP TABLE IF EXISTS document;
DROP TABLE IF EXISTS professional_request;
DROP TABLE IF EXISTS announcement_locker;
DROP TABLE IF EXISTS announcement;
DROP TABLE IF EXISTS event;
DROP TABLE IF EXISTS formation;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS locker;
DROP TABLE IF EXISTS permission;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS topic;
DROP TABLE IF EXISTS ticket;
DROP TABLE IF EXISTS subscription_plans;
DROP TABLE IF EXISTS subscription;
DROP TABLE IF EXISTS payement;
DROP TABLE IF EXISTS notification;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS advice;
DROP TABLE IF EXISTS user;

SET FOREIGN_KEY_CHECKS = 1;
