ALTER TABLE `event`     ADD COLUMN `deleted_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `formation` ADD COLUMN `deleted_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `user`      ADD COLUMN `deleted_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `category`  ADD COLUMN `deleted_at` DATETIME NULL DEFAULT NULL;
