SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM SUB_SUB_PLAN
WHERE id_subscription IN ('TEST-SUB-0001','TEST-SUB-0002');

DELETE FROM USER_SUBSCRIPTION
WHERE id_subscription IN ('TEST-SUB-0001','TEST-SUB-0002');

DELETE FROM PAYEMENT_PROJECT
WHERE id_payement IN ('TEST-PAY-0001','TEST-PAY-0002');

DELETE FROM PAYEMENT_EVENT
WHERE id_payement IN ('TEST-PAY-0001','TEST-PAY-0002');

DELETE FROM PAYEMENT_FORMATION
WHERE id_payement IN ('TEST-PAY-0001','TEST-PAY-0002');

DELETE FROM USER_PAYEMENT
WHERE id_payement IN ('TEST-PAY-0001','TEST-PAY-0002');

DELETE FROM USER_NOTIFICATION
WHERE id_notification IN ('TEST-NOTIF-0001','TEST-NOTIF-0002');

DELETE FROM USER_TICKET
WHERE id_ticket IN ('TEST-TICKET-0001','TEST-TICKET-0002');

DELETE FROM USER_EVENT_INSCRIPTION
WHERE id_event IN ('TEST-EVENT-0001','TEST-EVENT-0002');

DELETE FROM USER_EVENT
WHERE id_event IN ('TEST-EVENT-0001','TEST-EVENT-0002');

DELETE FROM USER_FORMATION_INSCRIPTION_PAYEMENT
WHERE id_payement IN ('TEST-PAY-0001','TEST-PAY-0002');

DELETE FROM USER_FORMATION_INSCRIPTION
WHERE id_formation IN ('TEST-FORM-0001','TEST-FORM-0002');

DELETE FROM USER_FORMATION_CREATE
WHERE id_formation IN ('TEST-FORM-0001','TEST-FORM-0002');

DELETE FROM USER_FORMATION_FORMATER
WHERE id_formation IN ('TEST-FORM-0001','TEST-FORM-0002');

DELETE FROM USER_PROJECT_UPDOWN
WHERE id_project IN ('TEST-PROJ-0001','TEST-PROJ-0002');

DELETE FROM USER_PROJECT_INSCRIPTION
WHERE id_project IN ('TEST-PROJ-0001','TEST-PROJ-0002');

DELETE FROM USER_PROJECT_CREATE
WHERE id_project IN ('TEST-PROJ-0001','TEST-PROJ-0002');

DELETE FROM TOPIC_POST
WHERE id_topic IN ('TEST-TOPIC-0001','TEST-TOPIC-0002');

DELETE FROM USER_TOPIC
WHERE id_topic IN ('TEST-TOPIC-0001','TEST-TOPIC-0002');

DELETE FROM USER_ADVICE
WHERE id_advice IN ('TEST-ADV-0001','TEST-ADV-0002');

DELETE FROM ANNOUNCEMENT_LOCKER
WHERE id_announcement IN ('TEST-ANN-0001','TEST-ANN-0002');

DELETE FROM USER_ANNOUNCEMENT
WHERE id_announcement IN ('TEST-ANN-0001','TEST-ANN-0002');

DELETE FROM USER_ROLE
WHERE id_role IN ('TEST-ROLE-0001','TEST-ROLE-0002');

DELETE FROM REPORT_POST
WHERE id_report_post IN ('TEST-RPOST-0001','TEST-RPOST-0002');

DELETE FROM REPORT_TOPIC
WHERE id_report_topic IN ('TEST-RTOP-0001','TEST-RTOP-0002');

DELETE FROM REPORT_ANNOUCEMENT
WHERE id_report_annoucement IN ('TEST-RANN-0001','TEST-RANN-0002');

DELETE FROM DOCUMENT
WHERE id_document IN ('TEST-DOC-0001','TEST-DOC-0002');

DELETE FROM LOCKER
WHERE id_locker IN ('TEST-LOCK-0001','TEST-LOCK-0002');

DELETE FROM ANNOUNCEMENT
WHERE id_announcement IN ('TEST-ANN-0001','TEST-ANN-0002');

DELETE FROM PAYEMENT
WHERE id_payement IN ('TEST-PAY-0001','TEST-PAY-0002');

DELETE FROM SUBSCRIPTION
WHERE id_subscription IN ('TEST-SUB-0001','TEST-SUB-0002');

DELETE FROM SUBSCRIPTION_PLANS
WHERE id_plan IN ('TEST-PLAN-0001','TEST-PLAN-0002');

DELETE FROM ADVICE
WHERE id_advice IN ('TEST-ADV-0001','TEST-ADV-0002');

DELETE FROM POST
WHERE id_post IN ('TEST-POST-0001','TEST-POST-0002');

DELETE FROM TOPIC
WHERE id_topic IN ('TEST-TOPIC-0001','TEST-TOPIC-0002');

DELETE FROM PROJECT
WHERE id_project IN ('TEST-PROJ-0001','TEST-PROJ-0002');

DELETE FROM FORMATION
WHERE id_formation IN ('TEST-FORM-0001','TEST-FORM-0002');

DELETE FROM EVENT
WHERE id_event IN ('TEST-EVENT-0001','TEST-EVENT-0002');

DELETE FROM TICKET
WHERE id_ticket IN ('TEST-TICKET-0001','TEST-TICKET-0002');

DELETE FROM NOTIFICATION
WHERE id_notification IN ('TEST-NOTIF-0001','TEST-NOTIF-0002');

DELETE FROM ROLE
WHERE id_role IN ('TEST-ROLE-0001','TEST-ROLE-0002');

DELETE FROM USER
WHERE id_user IN ('TEST-USER-0001','TEST-USER-0002');

SET FOREIGN_KEY_CHECKS = 1;